import TechnologyWrapper from '../common/TechnologyWrapper';
import Skills from './styles';

export default function SkillsWrapper() {
  return (
    <Skills
      id="skills"
    >
      <Skills.Title>
        {'<Habilidades />'}
      </Skills.Title>
      <Skills.Technologies>
        <TechnologyWrapper
          src="/images/html.webp"
          alt="Image"
        >
          HTML 5
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/css.webp"
          alt="Image"
        >
          CSS 3
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/javascript.webp"
          alt="Image"
        >
          Javascript
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/react.webp"
          alt="Image"
        >
          React
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/styled-components.webp"
          alt="Image"
        >
          Styled-Components
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/git.webp"
          alt="Image"
        >
          Git
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/github.webp"
          alt="Image"
        >
          Github
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/next.webp"
          alt="Image"
        >
          Next
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/bootstrap.webp"
          alt="Image"
        >
          Bootstrap
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/sass.webp"
          alt="Image"
        >
          Sass
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/tailwindcss.webp"
          alt="Image"
        >
          Tailwindcss
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/typescript.webp"
          alt="Image"
        >
          Typescript
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/docker.webp"
          alt="Image"
        >
          Docker
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/node.webp"
          alt="Image"
        >
          Node
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/express.webp"
          alt="Image"
        >
          Express
        </TechnologyWrapper>
        <TechnologyWrapper
          src="/images/postgresql.webp"
          alt="Image"
        >
          PostgreSQL
        </TechnologyWrapper>
      </Skills.Technologies>
    </Skills>
  );
}
